default: all

all:
	# "building city data reader example"
	g++ -O -Wall -o datareader datareader.cpp
	g++ -O -Wall -o sales sales.cpp
	g++ -O -Wall -o sales_redo sales_redo.cpp
	g++ -O -Wall -o sales_redo_c sales_redo_c.cpp

clean:
	rm -f datareader sales *~ *png
	rm -f datareader *~ *png
	rm -f sales_redo *~ *png
	rm -f sales_redo_c *~ *png
